### PR TITLE
PMM-10353 Fix of validators errors in core-ui

### PR DESCRIPTION
**Pull request by atymchuk**
fix of problem with displaing error of email and maxLength validators when field is empty and not required
https://jira.percona.com/browse/PMM-10353

### CODE REVIEW

**Review by solovevayaroslavna — APPROVED** [review]

**Comment by solovevayaroslavna** [comment]
@atymchuk I can't add the same test as for maxLength for the email validator, becouse email validator allows passing only strings directly inside it, so I created test in textInputField for checking it with fireEvent.onchange(), is it okey or not?

**Comment by atymchuk** [comment]
> @atymchuk I can't add the same test as for maxLength for the email validator, becouse email validator allows passing only strings directly inside it, so I created test in textInputField for checking it with fireEvent.onchange(), is it okey or not?

I added [a test](https://github.com/percona-platform/core-ui/pull/68/files#diff-c1fef324aa84f5a8dead39d6568be95198e7537c25ce7af03a4dfecbad631fdaR26) for `email` :)

**Comment by solovevayaroslavna** [comment]
@atymchuk thought that we should avoid varnings) Can we merge it now?  (Should  I delete extra test for email validator in textInoutField (https://github.com/percona-platform/core-ui/pull/68/files#:~:text=it(%22shouldn%27t%20show%20validation%20error%20of%20email%20if%20field%20is%20not%20required%22%2C%20async%20()%20%3D%3E%20%7B) or we can leave it?)
image

**Comment by atymchuk** [comment]
> thought that we should avoid varnings.

Yes, we should avoid warning, so I updated the code. Passing `undefined` is still a good test since we know there are real use cases for it.

**Comment by atymchuk** [comment]
> Should I delete extra test for email validator in textInoutField

No, let it be there :)

**Pull request merged**
